name: DigiCoin
author: Flenix
main: co.uk.silvania.cities.digicoin.DigiCoin
version: 0.1
depend: [Vault]

commands:
  digicoin:
    aliases: [ econ, wallet, money ]
    description: Balance command

permissions:
  digicoin.pay:
    description: Lets you pay a player.
  digicoin.admin:
    description: Lets you use admin commands.
    default: op
  digicoin.balance:
    description: Lets you see anyones balance.
    default: op